import type { NextPage } from "next";
import Head from "next/head";
import {
  createTheme,
  StyledEngineProvider,
  ThemeProvider,
} from "@mui/material/styles";
import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";
import { globalTheme } from "../utils/theme";
import CssBaseline from "@mui/material/CssBaseline";
import Home from "./Home";

const theme = createTheme({
  palette: {
    primary: {
      light: globalTheme.light,
      main: globalTheme.primary,
      dark: globalTheme.dark,
    },
    secondary: {
      light: "#ff7961",
      main: "#f44336",
      dark: "#ba000d",
      contrastText: "#000",
    },
  },
});

const cache = createCache({
  key: "css",
  prepend: true,
});

const App: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledEngineProvider injectFirst>
        <CacheProvider value={cache}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Home />
          </ThemeProvider>
        </CacheProvider>
      </StyledEngineProvider>
    </>
  );
};

export default App;
